/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_rasmusantons_cubiomes_Generator */

#ifndef _Included_de_rasmusantons_cubiomes_Generator
#define _Included_de_rasmusantons_cubiomes_Generator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_rasmusantons_cubiomes_Generator
 * Method:    getStateSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_rasmusantons_cubiomes_Generator_getStateSize
  (JNIEnv *, jobject);

/*
 * Class:     de_rasmusantons_cubiomes_Generator
 * Method:    setupGenerator
 * Signature: (Lde/rasmusantons/cubiomes/MCVersion;I)V
 */
JNIEXPORT void JNICALL Java_de_rasmusantons_cubiomes_Generator_setupGenerator
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     de_rasmusantons_cubiomes_Generator
 * Method:    applySeed
 * Signature: (Lde/rasmusantons/cubiomes/Dimension;J)V
 */
JNIEXPORT void JNICALL Java_de_rasmusantons_cubiomes_Generator_applySeed
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     de_rasmusantons_cubiomes_Generator
 * Method:    getBiomeAt
 * Signature: (IIII)Lde/rasmusantons/cubiomes/BiomeID;
 */
JNIEXPORT jobject JNICALL Java_de_rasmusantons_cubiomes_Generator_getBiomeAt
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     de_rasmusantons_cubiomes_Generator
 * Method:    genBiomes
 * Signature: (Lde/rasmusantons/cubiomes/Range;)[Lde/rasmusantons/cubiomes/BiomeID;
 */
JNIEXPORT jobjectArray JNICALL Java_de_rasmusantons_cubiomes_Generator_genBiomes
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
