/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_rasmusantons_cubiomes_Cubiomes */

#ifndef _Included_de_rasmusantons_cubiomes_Cubiomes
#define _Included_de_rasmusantons_cubiomes_Cubiomes
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_rasmusantons_cubiomes_Cubiomes
 * Method:    getGeneratorSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_rasmusantons_cubiomes_Cubiomes_getGeneratorSize
  (JNIEnv *, jobject);

/*
 * Class:     de_rasmusantons_cubiomes_Cubiomes
 * Method:    setupGenerator
 * Signature: (Lde/rasmusantons/cubiomes/MCVersion;I)V
 */
JNIEXPORT void JNICALL Java_de_rasmusantons_cubiomes_Cubiomes_setupGenerator
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     de_rasmusantons_cubiomes_Cubiomes
 * Method:    applySeed
 * Signature: (Lde/rasmusantons/cubiomes/Dimension;J)V
 */
JNIEXPORT void JNICALL Java_de_rasmusantons_cubiomes_Cubiomes_applySeed
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     de_rasmusantons_cubiomes_Cubiomes
 * Method:    getBiomeAt
 * Signature: (IIII)Lde/rasmusantons/cubiomes/BiomeID;
 */
JNIEXPORT jobject JNICALL Java_de_rasmusantons_cubiomes_Cubiomes_getBiomeAt
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     de_rasmusantons_cubiomes_Cubiomes
 * Method:    genBiomes
 * Signature: (Lde/rasmusantons/cubiomes/Range;)[[[Lde/rasmusantons/cubiomes/BiomeID;
 */
JNIEXPORT jobjectArray JNICALL Java_de_rasmusantons_cubiomes_Cubiomes_genBiomes
  (JNIEnv *, jobject, jobject);

/*
 * Class:     de_rasmusantons_cubiomes_Cubiomes
 * Method:    getStructurePos
 * Signature: (Lde/rasmusantons/cubiomes/StructureType;JII)Lde/rasmusantons/cubiomes/Pos;
 */
JNIEXPORT jobject JNICALL Java_de_rasmusantons_cubiomes_Cubiomes_getStructurePos
  (JNIEnv *, jobject, jobject, jlong, jint, jint);

/*
 * Class:     de_rasmusantons_cubiomes_Cubiomes
 * Method:    isViableStructurePos
 * Signature: (Lde/rasmusantons/cubiomes/StructureType;II)Z
 */
JNIEXPORT jboolean JNICALL Java_de_rasmusantons_cubiomes_Cubiomes_isViableStructurePos
  (JNIEnv *, jobject, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
